import { test, expect } from '@playwright/test';
test('independent squeak setting persists, supports playback and resets', async ({page}) => {
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await page.getByRole('tab', {name:'설정',exact:true}).click();
  const squeak = page.getByRole('checkbox', {name:'줄 마찰음 감소',exact:false});
  const iir = page.getByRole('checkbox', {name:'iPhone to km184 - IIR',exact:false});
  await expect(squeak).not.toBeChecked();
  await squeak.check();
  await iir.check();
  await expect(squeak).toBeChecked();
  await iir.uncheck();
  await page.reload();
  await page.getByRole('tab', {name:'설정',exact:true}).click();
  await expect(squeak).toBeChecked();
  await expect(iir).not.toBeChecked();
  await page.getByRole('tab', {name:'연습',exact:true}).click();
  await expect(page.getByRole('button', {name:'Raw play',exact:true})).toBeVisible();
  await page.getByRole('button', {name:'구간 반복 OFF'}).click();
  await page.getByRole('button', {name:'녹음 시작',exact:true}).click();
  await expect(page.getByRole('button', {name:'정지하고 듣기'})).toBeEnabled();
  await page.waitForTimeout(700);
  await page.getByRole('button', {name:'정지하고 듣기'}).click();
  await expect(page.locator('.play-button')).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button', {name:'재생 정지',exact:true}).click();
  await page.getByRole('button', {name:'Raw play',exact:true}).click();
  await expect(page.locator('.raw-play-button')).toHaveAttribute('aria-pressed','true');
  await page.getByRole('tab', {name:'설정',exact:true}).click();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  page.once('dialog', dialog=>dialog.accept());
  await page.getByRole('button', {name:'로컬 데이터 모두 삭제'}).click();
  await expect(squeak).not.toBeChecked();
  await page.getByRole('tab', {name:'연습',exact:true}).click();
  await expect(page.getByRole('button', {name:'Play',exact:true})).toBeVisible();
  expect(errors).toEqual([]);
});
